language: node_js

node_js:
  - lts/*

install:
  - npm install
  - npm install --no-save booljs@latest @booljs/express

deploy:
  provider: npm
  email: hola@pablodorado.com
  api_key: $NPM_API_KEY
  on:
    branch: master
    tags: true